---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create tempest directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "{{ item.mode|default('0755') }}"
  with_items:
    - path: "{{ tempest_log_dir | realpath }}"
    - path: "{{ ansible_env.HOME }}/.tempest/etc"
    - path: "{{ tempest_image_dir }}"

- name: Copy tempest config
  config_template:
    src: "tempest.conf.j2"
    dest: "{{ ansible_env.HOME }}/.tempest/etc/tempest.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    config_overrides: "{{ tempest_tempest_conf_overrides }}"
    config_type: "ini"
  register: copy_tempest_config

- name: Move over workspace when config is updated
  shell: |
    set -e

    . {{ tempest_venv_bin }}/activate

    if tempest workspace list | grep ' workspace '; then

        # Get a backup suffix
        export CURDATE=$(date +"%d%^b%g_%H%M%S%Z")

        # Get the dirname for 'workspace' directly from the tempest workspace list
        WSPATH=$(dirname $(tempest workspace list | awk '{if($2 == "workspace"){print $4}}'))

        # Rename the workspace
        tempest workspace rename --old-name workspace --new-name workspace_${CURDATE}

        # A workspace move only changes the config.  The move happens manually.
        if [ -d "${WSPATH}/workspace" ]
        then
            mv ${WSPATH}/workspace ${WSPATH}/workspace_${CURDATE}
            tempest workspace move --name workspace_${CURDATE} --path ${WSPATH}/workspace_${CURDATE}/
        fi

        exit 3
    fi
  args:
    executable: /bin/bash
  register: tempest_move_workspace
  changed_when: tempest_move_workspace.rc == 3
  failed_when:
    - tempest_move_workspace.rc != 0
    - tempest_move_workspace.rc != 3
  when: copy_tempest_config.changed
  tags:
    # don't trigger ANSIBLE0016
    - skip_ansible_lint

- name: Initialise tempest workspace
  shell: |
    if [ ! -d {{ tempest_venv_bin | dirname }}/workspace ]
    then
      . {{ tempest_venv_bin }}/activate
      tempest init {{ tempest_venv_bin | dirname }}/workspace
      exit 3
    fi
  args:
    executable: /bin/bash
  register: tempest_init_workspace
  changed_when: tempest_init_workspace.rc == 3
  failed_when:
    - tempest_init_workspace.rc != 0
    - tempest_init_workspace.rc != 3
  tags:
    # don't trigger ANSIBLE0013
    - skip_ansible_lint

- name: Generate tempest test whitelist
  copy:
    content: |
      {% for item in tempest_test_whitelist | unique | sort %}
      {%   if item != '' %}
      {{ item }}
      {%   endif %}
      {% endfor %}
    dest: "{{ tempest_test_whitelist_file_path }}"

- name: Generate tempest test blacklist
  copy:
    content: |
      {% for item in tempest_test_blacklist | unique | sort %}
      {%   if item != '' %}
      {{ item }}
      {%   endif %}
      {% endfor %}
    dest: "{{ tempest_test_blacklist_file_path }}"
  when:
    - tempest_test_blacklist | length > 0

